[program:quanby-legal]
command=/var/www/quanby-legal/venv/bin/uvicorn main:app --host 127.0.0.1 --port 8080
directory=/var/www/quanby-legal/backend
autostart=true
autorestart=true
stderr_logfile=/var/log/quanby-legal.err.log
stdout_logfile=/var/log/quanby-legal.out.log
user=root
environment=HOME="/root",USER="root"
